### ISSUE TITLE
Missing a lot of Hotkey Options.

### ISSUE THREAD

**Issue by KaneHart** [bvbohnen/x4-projects#1]
Using:
better target monitor 1.4
extra game options 1.4
hotkeys 1.0
api 1.65
pip 1.1

![1yTzns0](https://user-images.githubusercontent.com/425853/79038459-6ad01c80-7ba7-11ea-8d86-d73bd6a6369d.png)

![image](https://user-images.githubusercontent.com/425853/79038483-97843400-7ba7-11ea-9863-9e8e910f2988.png)

**Comment by KaneHart** [comment]
I think your example of hotkeys is overriding?
https://steamuserimages-a.akamaihd.net/ugc/1020569817347229987/67F374A31A75A2C542BC1276B8656F7F3ACC2A5E/

Thanks.

**Comment by KaneHart** [comment]
Closing it seems the released on github are outdated or some are from steam. Using steam version worked and had larger file size / newer dates

**Comment by bvbohnen** [comment]
The hotkey collection needed a proper version bump, which it has now.  Thanks for the report.
