### ISSUE TITLE
Remove Dirty Glass not working in 5.00.475121 HF2

### ISSUE THREAD

**Issue by MrSmite** [bvbohnen/x4-projects#11]
OS: Win 7 Pro
X4: 5.00.475121 HF-2

Installed **_sn_remove_dirty_glass_v1.4_** to game's extensions folder, started a custom game with an Elite Sentinel and glass was still dirty. Tried moving the mod to documents folder but same result.

LOG:

> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='diffuse_map']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
> [General] 0.03 ======================================
> [General] 0.03 ======================================
> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='translucency_map']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
> [General] 0.03 ======================================
> [General] 0.03 ======================================
> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='diffuseStr']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
> [General] 0.03 ======================================
> [General] 0.03 ======================================
> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='diffuse_paintStr']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
> [General] 0.03 ======================================
> [General] 0.03 ======================================
> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='normalStr']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
> [General] 0.03 ======================================
> [General] 0.03 ======================================
> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='environmentStr']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
> [General] 0.03 ======================================
> [General] 0.03 ======================================
> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='diffuse_detailStr']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
> [General] 0.03 ======================================
> [General] 0.03 ======================================
> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='normal_detailStr']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
> [General] 0.03 ======================================
> [General] 0.03 ======================================
> [=ERROR=] 0.03 No matching node for path '/materiallibrary/collection[@name='p1effects'][2]/material[@name='p1_window_trim_01']/properties/property[@name='color_dirtStr']/@value' in patch file 'extensions\sn_remove_dirty_glass\libraries\material_library'. Skipping node.
>

**Comment by bvbohnen** [comment]
This suggests the new dlc is adding "p1effects" and "p1" collection nodes to the material library, messing up the xpaths the mod was using. While the existing 1.4 version works for me (with split and terran dlcs), I tweaked the xpaths in version 1.5 to hopefully work regardless of user extensions/dlc.

**Comment by MrSmite** [comment]
Thanks, I'll try to test it and post back in a day or two.

**Comment by MrSmite** [comment]
Works good with Avarice 5.0 Hotfix 4, thanks for the quick update.
