### ISSUE TITLE
x4_keys is not connected to the server (server V1.42, sn_hotkeys V1.07)

### ISSUE THREAD

**Issue by morgenrot68** [bvbohnen/x4-projects#13]
I did an X4 update from 3.3 to 5.10 hotfix 2. I had to update many mods as well. This included Pipe Server from 1.31 to 1.42 and SN_Mod_Support_Apis from 1.80 to 1.88.

But now Pipe Server no longer connects to x4_keys.  It always shows disconnect.

Can someone help me?

Edit: OS is Win 7

**Comment by bvbohnen** [comment]
It could be a permissions issue with the server, or just general win7 problems with x4 mods. The pipes lua file can be edited (near the top) to turn on error messages, which may give more insight.
