### ISSUE TITLE
Pithon server shows as disconnected in the extension options.

### ISSUE THREAD

**Issue by Brinnie1** [bvbohnen/x4-projects#17]
Hi, as the title says the pipe server is disconnected and consequently the mods that requires it are not working.

I am running win 10, off the C drive on a laptop. I am trying to sort this issue out as I need to upgrade my gaming pc to win 10, on the laptop is just a test to check compatibility I only mentioned in case it could be relevant, ex the fact that it is running from onboard graphics.

I play X4 on windows 7 and I am able to run the pipe server and mods.

The debug log says "[=ERROR=] 183.08 x4_python_host; winpipe.open_pipe error reason: access denied by OS"

A user says:

"Ok so the error you're getting indicates you don't have the proper security descriptor (SD) to access the named pipe. I know how SDs work in win32 programs but not entirely sure how they work for python. When a program opens a named pipe, it requests a specific SD be attached to manage which users can access it at what level (read, write, read/write). If no such request is made, a default SD is created and I think as part of Microsoft's "security overhaul", they don't allow generic SDs on named pipes with Windows 10."

Any help would be appreciated/

thanks

**Comment by bvbohnen** [comment]
The server tries to set up the pipe security settings for the user account. Run the server with the -v arg to get a message on account permission status. Or just try running as admin.

**Comment by Brinnie1** [comment]
Hi, before posting here I had already tried to run as administrator but it didn't change anything.
After your reply I have added the -v arg to the target box in the shortcut properties, when I ran it, the window opened and minimized.
I tried to run it as admin and since then it closes alltogether, now it stays open and in focus only if I start the exe without the argument and not in admin mode.

I find it odd that I should be having this problem using win 10 and feeling like I am the only one in the world having this issue, I say that because a whole WWW search for the error returned only one hit. I would think most user of the pipe server and x4 are running win 10.

I was going to ask you is it likely that I am having this problem cause I am running the game and server app from the system drive (although not from the program files folder) or because the laptop is somewhat underpowered like with onboard graphics and generally already struggling with running the game?

As I already mentioned, not being able to run the server on the laptop is not a problem, the machine is just a testing bench for the game at best, I want to sort this out so that when and if I manage to install win 10 on my gaming rig I won't have to deal with this then. My gaming station is a bit old but it runs X4 with the pipe server and my mods selection (up till now) decently enough on win 7.

thanks

**Comment by bvbohnen** [comment]
Run it from a cmd or powershell prompt to see any stdout or stderr messages after it closes.

**Comment by Brinnie1** [comment]
Goodmorning
I have run it via the cmd. The first time it opened a window that closed immediately afterwards.

As that didn't really do much towards solving the problem I tried to run the program again (doubleclicking on its icon) and it said :

"This app cannot run on your pc, to find a version for your pc check with the software publisher"

doing it via the command prompt produced the same results and in cmd windows outputted

"C:\Games\Steam\steamapps\common\X4 Foundations>X4_Python_Pipe_Server.exe
Access is denied."

Too strange to comprehend for me. I mean the app opened normally although it didn't work in game and that I can come to terms with, it's not rare that an app doesn't function as it should on a pc. What baffles me is how is it that the behaviour is evolving (or devolving), if you read the previous posts, I'll do you a round up so you don't need to go through them:

1 The app runs as normal but it shows as disconnected
2 I run the server with the -v arg. = The window opened and minimized.
3 Run it as admin. = It closes alltogether. It stayed open and in focus only if the exe is started without            the argument and not in admin mode.
4 Run the program in command line = The window opened and minimized and now ...

I realize I am ignorant on the matter but it is strange that this persisted even after a reboot.


I don't want to pester you so feel free to tell me to bugger off if would rather not waste time on this,
thanks

**Comment by Brinnie1** [comment]
A very quick update. 

I must have messed something up, I have noticed that the exe had become 0 bytes and this other file appeared "X4_Python_Pipe_Server.execcd" alongside it. Ignore my previous post.
 I will run through your guidelines from the start, taking my time so hopefully I won't mess up and then I ll post back.

bye for now
