### ISSUE TITLE
Using translated text for Simple Menu API

### ISSUE THREAD

**Issue by Vectorial1024** [bvbohnen/x4-projects#2]
Hi there, I'm trying to use your Simple Menu API to set extension options.

Following your example, I noticed that if I place e.g. `{221024, 100001}` into the `$mouseover`, I will get a `=ReadText221024-100001=` mouseover text on my extension options. Is there anything that I should do in order to make the mouseover display the actual translated text?

**Comment by bvbohnen** [comment]
That is the X4 fallback when it doesn't find a text entry, and is not specific to this api.

**Comment by Vectorial1024** [comment]
Thank you for the hint! I didn't realize there was a problem with my mod files when I was testing my mods, and now I have fixed this on my side.
