### ISSUE TITLE
tracker mines cannot be dropped via hotkey (sn_hotkey_collection_v1.4)

### ISSUE THREAD

**Issue by morgenrot68** [bvbohnen/x4-projects#7]
Concerns sn_hotkey_collection_v1.4

Hello,
Unfortunately, tracker mines cannot be dropped via the hotkey.
I get the message 'no tracker mines available'. But this is not true. There are enough in the ship.
All other consumables can be dropped via the hotkey, but no tracker mines.
Tracker mines are dropped via the vanilla menu, that works.

I also tried it in a mod-free installation to exclude a mod conflict.

German Version v3.3

**Comment by bvbohnen** [comment]
There are two tracker mine macros in the game files, and I was likely using the wrong one.  I swapped to weapon_gen_mine_02_macro and pushed the update.  Let me know if that doesn't fit it.

**Comment by morgenrot68** [comment]
Hello,
now it works perfectly! 
Thank you very much.

Are you interested in the German t-file? 
Then you would have to tell me where I can send it.

**Comment by bvbohnen** [comment]
Sure, you can share it however is convenient.  Since this is github, a pull request works.

**Comment by morgenrot68** [comment]
Hello,
unfortunately I don't know at all how it works with Github. I just looked at it and tried to make a pull request. Unfortunately it did not work. I would have to work more intensively with Github, but unfortunately I don't have the time at the moment. I only wanted to make the t-file available.

I am now copying it here as code.

0001-L049.xml

`<?xml version="1.0" encoding="utf-8" ?>
<language>
  
<page id="68537" title="SirNukes texts" descr="0" voice="no">
  
  
  <t id="4000">{1004,55}(Launch)</t>
  

  <t id="4000">Folge Ziel</t>
  <t id="4001">Schaltet den Autopiloten ein, um dem Ziel zu folgen, ohne dass das Missionsziel überschrieben werden muss</t>
  <t id="4002">Auswurf illegaler Waren</t>
  <t id="4003">Wirft jegliches Spielerinventar oder die Ladung von Pilotenschiffen aus, die in der Spielerzone illegal sind</t>

  <t id="4004">SETA Ein/Aus</t>
  <t id="4005">Schaltet den SETA-Modus um; im Gegensatz zum normalen Hotkey funktioniert dies im angedockten Zustand</t>

  <t id="4006">Heranzoomen</t>
  <t id="4007">Zoomt in die aktuelle Ansicht, während die Taste gedrückt wird.</t>
  
  
  <t id="4100">{1004,55} {20201,20101}(Tracker Mine)</t>
  <t id="4101">{1004,55} {20201,20201}(Mine)</t>
  <t id="4102">{1004,55} {20201,20301}(Satellite)</t>
  <t id="4103">{1004,55} {20201,20401}(Advanced Satellite)</t>
  <t id="4104">{1004,55} {20201,20501}(Laser Tower Mk1)</t>
  <t id="4105">{1004,55} {20201,20601}(Laser Tower Mk2)</t>
  <t id="4106">{1004,55} {20201,20701}(Resource Probe)</t>
  <t id="4107">{1004,55} {20201,20801}(Nav Beacon)</t>
  <t id="4108">{1004,55} {20201,20901}(Friend/Foe Mine)</t>
  <t id="4109">{1004,55} {20201,21001}(Cluster Mine)</t> 
  <t id="4120">Plaziert ein Objekt vom Spieler gesteuerten Schiff</t>

  <t id="4121">%s aufgestellt</t>
  <t id="4122">Keine %s vorhanden</t>

</page>

</language>`
