### ISSUE TITLE
Mod Support APIs crashes my existing save

### ISSUE THREAD

**Issue by Dan-Gecko** [bvbohnen/x4-projects#8]
stats: Win10 pro, X4, v4.10 with both DLCs
Hello!
I would need the Simple Menu API to run the mod Blueprint Analysis by marksmango. I did copy the folder 'sn_mod_support_apis' to my extensions folder in order to use the mod. 

When trying to load a save with the Mod Support APIs turned on, it charshes X4 and brings me to this crash report site (by egosoft) [Link](https://www.egosoft.com:8443/jira/browse/X4-511). Another person referenced Simple Menu API as a cause for the crash there already, though it's some time ago. How can I use the Mod Support APIs without crashing? Am I missing something?

**Comment by bvbohnen** [comment]
This is the first I've heard of it crashing for some people.  Sorry about that, but the ego crash report doesn't give me much to go on, so it's hard to debug from here.

Does it crash if you start a new game with no other extensions enabled except egosoft dlcs?

**Comment by Dan-Gecko** [comment]
Yes, the game does crash with Mod Support APIs enabled as the only mod in addition to both DLCs. To be absolutely sure, I removed the entire extensions folder and only put back the 3 mods in question. 
The one thing I have different than default installation: I am using a symlink for the "save" folder to rout it to an internal M.2 SSD for faster saving. The game is also on the same M.2 SSD. (windows runs on an isolated SATA SSD because of the wear windows has on hard drives. Using this "symlink" was the only way I found to move the save game location from the slower SATA SSD to the faster M.2 SSD)

**Comment by bvbohnen** [comment]
Well, mods shouldn't be run out of the documents folder anyway (path references break), so that's fine.  Is there anything interesting at the end of the x4 debug log before the crash?  (Logging is enabled with the X4 command line arg "-logfile debuglog.txt", written to the documents folder.)

**Comment by Dan-Gecko** [comment]
There is a bunch going on! From the comparison I don't see anything really different from the mod crash and without, though. Please take a look yourself. Let me know if I can be of any other help in solving this problem. I would really like to use that mod... 

[debuglog_ModOn.txt](https://github.com/bvbohnen/x4-projects/files/6175282/debuglog.txt)
[debuglog_ModOff.txt](https://github.com/bvbohnen/x4-projects/files/6175285/debuglog.txt)

**Comment by Vectorial1024** [comment]
Just another X4 Foundations mod chiming in.

> [General] 0.00 'GeForce RTX 3080' NVIDIA-driver v461.72.0 (Vulkan 1.2.155) check=1

That is a big red flag. EgoSoft specifically announced in 4.0 release that they are having problems with the NVIDIA GeForce RTX 30xx Series GPUs (source: https://store.steampowered.com/news/app/392160/view/3053976758966787078), so it might not even be related to Mod Support API.

Try running the game with absolutely no mods.

**Comment by bvbohnen** [comment]
I notice there are several duplicate file errors, eg. "[=ERROR=] 86804.05 Skipping MD file extensions\sn_mod_support_apis\md\Simple_Menu_API.xml: Script name 'Simple_Menu_API' already found in file extensions\sn_mod_support_apis\md\simple_menu_api.xml".  Please try deleting the sn_mod_support_apis folder entirely and replacing it with the latest version from Releases (1.82).

**Comment by Dan-Gecko** [comment]
Your input is noted, Vectorial1024! Though, unless proven otherwise (or me actually experiencing a crash of described nature) I don't see how this is related to my crash at all. If you follow the conversation from the start, you will easily see, the crash was only happening in conjunction with Simple_Menu_API interfering with any of my other mods or just itself causing the issue. As I said, at this point I am fairly certain the crash is not caused by my EVGA RTX 3080 FTW Ultra ;) cheers!
----------------------------------------------------------------------
Now, on the topic:
By using the version you recommended (version from Releases (1.82)) I do not encounter the crash any more. I did re-install the game from scratch, removed the symlink and cleaned out my mods folder from mods I don't intend to use any more. I don't know what you did or if it was my doing (and consequently my fault), but thank you so much for your help and time spent, dear bvbohnen!! Very much appreciated!
